services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_local
    restart: unless-stopped
    ports:
      - "6333:6333"   # HTTP
      - "6334:6334"   # gRPC
    volumes:
      - ./qdrant_data:/qdrant/storage
      # - ./qdrant_config/config.yaml:/qdrant/config/production.yaml:ro   # <â€” comentar por ahora

